### PR TITLE
Improve poms and update to Java 11

### PR DESCRIPTION
**Pull request by EdwardKuenen**

### CODE REVIEW

**Comment by brusdev** [comment]
@EdwardKuenen thanks for splitting your changes on multiple commits. Do you mind if I amend your commit message before merging your PR to `Update poms to Java 11` (of course I will not change the commit author)?

**Comment by jbertram** [comment]
LGTM

**Comment by brusdev** [comment]
@EdwardKuenen I amended your commit using git commit --amend (of course I didn't change the commit author) and then I pushed your branch with the force option using git push ekuenen only-pom-improvement -f, I'll merge this PR in 1h unless you have any concerns.

**Comment by EdwardKuenen** [comment]
Thank you very much! Will there be a new release of this version?

**Comment by brusdev** [comment]
@EdwardKuenen thanks for your contribution, I should create a release tag tomorrow.

**Pull request merged**
