### PR TITLE
fix: resolve NoClassDefFoundError for jakarta.servlet.http.HttpServlet

### PR DESCRIPTION
**Pull request by Jean-Emile**

### CODE REVIEW

**Comment by brusdev** [comment]
@Jean-Emile artemis-prometheus-metrics-plugin 3.x was intentionally updated to jakarta.servlet. You can use artemis-prometheus-metrics-plugin 2.x for ActiveMQArtemis versions that require javax.servlet.

**Comment by evannorstrand-mp** [comment]
@brusdev - I am using the latest artemis release which is 2.33.0 created ~15 days ago, and this issue is occurring.  Which version should I be using?

**Comment by brusdev** [comment]
@Jean-Emile artemis-prometheus-metrics-plugin 3.x is for future ActiveMQArtemis versions, you can use artemis-prometheus-metrics-plugin 2.1.0 for ActiveMQArtemis 2.33.0.

**Comment by smithpj** [comment]
I ran into this issue when running artemis 2.32 on Java 17.  I applied the patch that was closed/not merged here and recompiled with those jakarta/javax changes and it solved the issue for me.

**Comment by brusdev** [comment]
@smithpj what artemis-prometheus-metrics-plugin version should I use to reproduce your issue with artemis 2.32 on Java 17?

**Comment by smithpj** [comment]
I was running artemis-prometheus-metrics-plugin 3.0 (not knowing it wasn't for artemis 2.32).  The changes in the patch to use javax over jakarta and other minor things in this PR did get metrics working for me however.

**Comment by brusdev** [comment]
@smithpj I confirm artemis-prometheus-metrics-plugin 3.0 must not be used with artemis 2.32,  have you tried artemis-prometheus-metrics-plugin 2.1.0  with artemis 2.32 on Java 17?

**Comment by brusdev** [comment]
@smithpj there are no plan yet for a newer Apache ActiveMQ Artemis version that requires the 3.0 plugin. Please use the 2.x plugin.

**Pull request closed without merging**
